Examen/Controllers/KlantsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Examen.Models;

namespace Examen.Controllers
{
    [Authorize]
    public class KlantsController : Controller
    {
        private DatabaseEntities db = new DatabaseEntities();

        // GET: Klants
        public async Task<ActionResult> Index()
        {
            return View(await db.Klant.ToListAsync());
        }

        // GET: Klants/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Klant klant = await db.Klant.FindAsync(id);
            if (klant == null)
            {
                return HttpNotFound();
            }
            return View(klant);
        }

        // GET: Klants/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Klants/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Naam,Telefoon,Status")] Klant klant)
        {
            if (ModelState.IsValid)
            {
                db.Klant.Add(klant);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(klant);
        }

        // GET: Klants/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Klant klant = await db.Klant.FindAsync(id);
            if (klant == null)
            {
                return HttpNotFound();
            }
            return View(klant);
        }

        // POST: Klants/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Naam,Telefoon,Status")] Klant klant)
        {
            if (ModelState.IsValid)
            {
                db.Entry(klant).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(klant);
        }

        // GET: Klants/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Klant klant = await db.Klant.FindAsync(id);
            if (klant == null)
            {
                return HttpNotFound();
            }
            return View(klant);
        }

        // POST: Klants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Klant klant = await db.Klant.FindAsync(id);
            db.Klant.Remove(klant);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Examen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="SHORTCUT ICON" href="~/Content/Images/favicon.ico"/>
    <title>Excellent Taste</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                 
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("Index", "Home")">
                            <img alt="Widget View" src="@Url.Content("~/content/images/favicon.png")">
                        </a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Nieuwe bestelling", "Create", "Bestellings")</li>
                        <li>@Html.ActionLink("Barman", "Barman", "ConsumptieItems")</li>
                        <li>@Html.ActionLink("Chef kok", "ChefKok", "ConsumptieItems")</li>
                        <li>@Html.ActionLink("ConsumptieItems", "index", "ConsumptieItems")</li>
                        <li>@Html.ActionLink("ConsumptieGroep", "Index", "ConsumptieGroeps")</li>
                        <li>@Html.ActionLink("Consumptie", "Index", "Consumpties")</li>
                        <li>@Html.ActionLink("MenuKaart", "MenuKaart", "ConsumptieItems")</li>
                        <li>@Html.ActionLink("Reservering", "Index", "Reserverings")</li>
                        <li>@Html.ActionLink("Klant", "Index", "Klants")</li>
                        @Html.Partial("_LoginPartial")
                    }
                    else
                    {
                        @Html.Partial("_LoginPartial")
                    }
                </ul>           
            </div>
        </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
       
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>